#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx
sudo apt-get -y install ufw
# Start Nginx service
sudo service nginx start

# Allow Nginx through firewall
sudo ufw allow "Nginx HTTP"

# Set ownership of index file
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html

# Write "Hello World!" to index file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx service
sudo service nginx restart

